import AppKit
import Foundation

final class ClipboardWatcher {
    /// Markers defined by nspasteboard.org. Password managers set ConcealedType so history tools skip the entry.
    private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let store: Store
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: DispatchSourceTimer?
    private let onChange: () -> Void

    /// Set while the app writes to the pasteboard itself, so re-copying an item does not create a duplicate read.
    private var suppressedChangeCount: Int?

    init(store: Store, onChange: @escaping () -> Void) {
        self.store = store
        self.onChange = onChange
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let timer = DispatchSource.makeTimerSource(queue: .main)
        timer.schedule(deadline: .now() + 0.3, repeating: 0.3)
        timer.setEventHandler { [weak self] in self?.poll() }
        timer.resume()
        self.timer = timer
    }

    func stop() {
        self.timer?.cancel()
        self.timer = nil
    }

    /// Writes text back to the pasteboard without the watcher re-ingesting it.
    func copyBack(_ item: ClipItem) {
        self.pasteboard.clearContents()
        switch item.kind {
        case .text:
            if let text = item.text { self.pasteboard.setString(text, forType: .string) }
        case .image:
            if let path = item.imagePath, let image = NSImage(contentsOfFile: path) {
                self.pasteboard.writeObjects([image])
            }
        }
        self.suppressedChangeCount = self.pasteboard.changeCount
        self.lastChangeCount = self.pasteboard.changeCount
    }

    private func poll() {
        let current = self.pasteboard.changeCount
        guard current != self.lastChangeCount else { return }
        self.lastChangeCount = current

        if let suppressed = self.suppressedChangeCount, suppressed == current {
            self.suppressedChangeCount = nil
            return
        }

        guard let types = pasteboard.types else { return }
        guard Self.skipTypes.isDisjoint(with: Set(types)) else { return }

        let app = NSWorkspace.shared.frontmostApplication?.localizedName

        if let data = imageData(from: types) {
            let thumbnail = Self.thumbnail(from: data.bytes)
            if self.store.upsertImage(data: data.bytes, fileExtension: data.ext, thumbnail: thumbnail, sourceApp: app) {
                self.store.enforceRetention(
                    maxImages: Settings.maxImagesNow,
                    maxBytes: Settings.maxImageBytesNow,
                    maxTexts: Settings.maxTextsNow
                )
            }
            self.onChange()
            return
        }

        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            self.store.upsertText(text, source: .clipboard, sourceApp: app)
            self.onChange()
        }
    }

    private func imageData(from types: [NSPasteboard.PasteboardType]) -> (bytes: Data, ext: String)? {
        if types.contains(.png), let data = pasteboard.data(forType: .png) {
            return (data, "png")
        }
        if types.contains(.tiff), let data = pasteboard.data(forType: .tiff) {
            guard let rep = NSBitmapImageRep(data: data),
                  let png = rep.representation(using: .png, properties: [:])
            else { return (data, "tiff") }
            return (png, "png")
        }
        return nil
    }

    private static func thumbnail(from data: Data, maxWidth: CGFloat = 160) -> Data? {
        guard let source = NSBitmapImageRep(data: data) else { return nil }
        let width = CGFloat(source.pixelsWide)
        let height = CGFloat(source.pixelsHigh)
        guard width > 0, height > 0 else { return nil }

        let scale = min(1, maxWidth / width)
        let targetSize = NSSize(width: (width * scale).rounded(), height: (height * scale).rounded())

        guard let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: Int(targetSize.width),
            pixelsHigh: Int(targetSize.height),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: target)
        source.draw(in: NSRect(origin: .zero, size: targetSize))
        NSGraphicsContext.restoreGraphicsState()

        return target.representation(using: .png, properties: [:])
    }
}
